name: barbearia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.2.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.1
  spacer: ^1.0.0
  syncfusion_flutter_calendar: ^26.1.39
  syncfusion_flutter_charts: ^26.1.39
  syncfusion_flutter_core: ^26.1.39
  syncfusion_flutter_datepicker: ^26.1.39
  drop_down_search_field: ^1.0.4
  mask_text_input_formatter: ^2.9.0
  extended_masked_text: ^3.0.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0
  get_storage: ^2.1.1
  supabase_flutter: ^2.5.6
  flex_color_picker: ^3.5.1
  toastification: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
