// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAKJP3MgE2YFgjSm_eR5z_Y58ZEMTScPuo',
//     appId: '1:718433769016:web:d8518b8e03b77af539f8cd',
//     messagingSenderId: '718433769016',
//     projectId: 'betas-projects',
//     authDomain: 'betas-projects.firebaseapp.com',
//     databaseURL: 'https://betas-projects.firebaseio.com',
//     storageBucket: 'betas-projects.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCcQ1HQ817N7uLwQLNV3YoCk_raZx_M0N8',
//     appId: '1:718433769016:android:c45a41151977a55639f8cd',
//     messagingSenderId: '718433769016',
//     projectId: 'betas-projects',
//     databaseURL: 'https://betas-projects.firebaseio.com',
//     storageBucket: 'betas-projects.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCq30phby1Xq9GRn6sdHmNtkuxIpBUTe5c',
//     appId: '1:718433769016:ios:bb26cf7ccb204bcb39f8cd',
//     messagingSenderId: '718433769016',
//     projectId: 'betas-projects',
//     databaseURL: 'https://betas-projects.firebaseio.com',
//     storageBucket: 'betas-projects.appspot.com',
//     androidClientId: '718433769016-d4a1p47dlt4iq49e18nip27947i11q97.apps.googleusercontent.com',
//     iosClientId: '718433769016-mi09r01uak119umnfuggv3l6k3qal4lg.apps.googleusercontent.com',
//     iosBundleId: 'com.example.barbearia',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCq30phby1Xq9GRn6sdHmNtkuxIpBUTe5c',
//     appId: '1:718433769016:ios:bb26cf7ccb204bcb39f8cd',
//     messagingSenderId: '718433769016',
//     projectId: 'betas-projects',
//     databaseURL: 'https://betas-projects.firebaseio.com',
//     storageBucket: 'betas-projects.appspot.com',
//     androidClientId: '718433769016-d4a1p47dlt4iq49e18nip27947i11q97.apps.googleusercontent.com',
//     iosClientId: '718433769016-mi09r01uak119umnfuggv3l6k3qal4lg.apps.googleusercontent.com',
//     iosBundleId: 'com.example.barbearia',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAKJP3MgE2YFgjSm_eR5z_Y58ZEMTScPuo',
//     appId: '1:718433769016:web:ba7f693a562b041f39f8cd',
//     messagingSenderId: '718433769016',
//     projectId: 'betas-projects',
//     authDomain: 'betas-projects.firebaseapp.com',
//     databaseURL: 'https://betas-projects.firebaseio.com',
//     storageBucket: 'betas-projects.appspot.com',
//   );
// }
